steps:  
  - name: 'docker'
    args: ['build', '-t', 'edgartf3/exemplo-arquitetura:latest', '-t', 'edgartf3/exemplo-arquitetura:$SHORT_SHA', '.']
  
  - name: 'docker'
    args: ['run', '-d', '--name', 'fortest', 'edgartf3/exemplo-arquitetura:latest']

  - name: 'docker'
    args: ['exec', 'fortest', 'pytest']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=$$USERNAME --password=$$PASSWORD']
    secretEnv: ['USERNAME', 'PASSWORD']

  - name: 'docker'
    args: ['push', 'edgartf3/exemplo-arquitetura:latest']

  - name: 'docker'
    args: ['push', 'edgartf3/exemplo-arquitetura:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: [
      'set',
      'image',
      'deployment',
      'exemploapp',
      'exemploapp=edgartf3/exemplo-arquitetura:$SHORT_SHA'
    ]
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=southamerica-east1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-1'

availableSecrets:
  secretManager:
  - versionName: projects/360880746501/secrets/docker-password/versions/1
    env: 'PASSWORD'
  - versionName: projects/360880746501/secrets/docker-user/versions/1
    env: 'USERNAME'
