apiVersion: apps/v1
kind: Deployment
metadata:
  name: exemploapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exemploapp
  template:
    metadata:
      labels:
        app: exemploapp
    spec:
      containers:
        - name: exemploapp
          image: edgartf3/exemplo-arquitetura:latest
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: exemploapp-service
  labels:
    app: exemploapp
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http-svc
      port: 80
      targetPort: 8000
  selector:
    app: exemploapp
