apiVersion: apps/v1
kind: Deployment
metadata:
  name: exemploserver
  labels:
    app: exemploserver
spec:
  selector:
    matchLabels:
      app: exemploserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "exemploserver"
    spec:
      containers:
        - name: exemploserver
          image: edgartf3/exemplo-arquitetura:v1
          envFrom:
            - configMapRef:
                name: exemploserver-env