apiVersion: v1
kind: Service
metadata:
  name: exemploserver-service
spec:
  selector:
    app: exemploserver
  type: ClusterIP
  ports:
  - name: exemploserver-service
    port: 8000
    protocol: TCP
    targetPort: 8000
