name: ci

on:
  push:
    branches: develop

jobs:
  build:
    name: docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
      - uses: actions/checkout@v3      
        run: docker build . --file dockerfile --tag edgartf3/exemplo-arquitetura:latest

      - name: Push Docker Image
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: edgartf3/exemplo-arquitetura:latest