name: ci

on:
  push:
    branches: develop

jobs:
  build:
    name: docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
      - uses: actions/checkout@v3      
        run: docker build . --file dockerfile --tag edgartf3/exemplo-arquitetura:latest