name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build:
    name: docker-image
    runs-on: ubuntu-latest

    steps: 
      - name: Login to DockerHub
      - uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
      - uses: actions/checkout@v3      
        run: docker build . --file dockerfile --tag edgartf3/exemplo-arquitetura:$(date +%s)
